-- Seed: 6 beginner-friendly blog posts (simple language, bullet points).
-- Vibe-coding focused. Safe to re-run: upserts on slug.
insert into public.blogs (slug, title, excerpt, content, author, published)
values
  ('what-is-vibe-coding', 'What is Vibe Coding?', 'Building software by describing what you want — and letting AI help write it.', E'Vibe coding is a new, easy way to build apps.\n\nThe simple idea:\n- You describe what you want in plain words\n- AI helps write the code\n- You check it, run it, and improve it\n- You ship a real product faster\n\nWhy people love it:\n- Less memorising of syntax\n- Focus on ideas, not just typing\n- Beginners can build real things sooner\n- You still learn how code works\n\nWhat you still need:\n- Basic understanding of how apps work\n- Ability to read and fix code\n- Good taste and clear thinking\n\nVibe coding does not replace learning. It makes learning faster and more fun.', 'KnowCode Team', true),

  ('5-ai-tools-for-beginners', '5 AI Tools Every Beginner Coder Should Try', 'Simple AI tools that help you write, fix and understand code.', E'AI tools make coding easier. Here are 5 to start with.\n\n1. AI chat assistant\n- Ask questions in plain English\n- Get code examples instantly\n\n2. Code completion\n- Suggests the next line as you type\n- Saves time and typos\n\n3. Bug explainer\n- Paste an error, get a simple fix\n- Learn why it happened\n\n4. Code-to-words\n- Explains what any code does\n- Great for understanding examples\n\n5. AI design helpers\n- Turn ideas into layouts fast\n\nTip: use AI to learn, not just to copy. Always read what it gives you.', 'KnowCode Team', true),

  ('build-your-first-website', 'How to Build Your First Website (No Experience Needed)', 'A simple, step-by-step path from zero to your first live page.', E'Anyone can build a website. Here is the simple path.\n\nStep 1: Learn the 3 basics\n- HTML = structure\n- CSS = style\n- JavaScript = action\n\nStep 2: Build something small\n- A page about you\n- Add a photo, some text, a button\n\nStep 3: Make it look good\n- Pick 2 colors\n- Use clear spacing\n- Keep it simple\n\nStep 4: Put it online\n- Use a free host\n- Share the link\n\nStep 5: Keep improving\n- Add one new thing each week\n\nYou learn fastest by building. Start today.', 'KnowCode Team', true),

  ('vibe-coding-vs-traditional', 'Vibe Coding vs Traditional Coding', 'Two ways to build — and when to use each one.', E'Both ways are useful. Here is the difference, simply.\n\nTraditional coding:\n- You write most code by hand\n- Slower at first\n- Deep control and understanding\n\nVibe coding:\n- You describe, AI helps write\n- Much faster to a working app\n- You guide and fix\n\nWhen to use traditional:\n- Learning the fundamentals\n- Tricky, custom logic\n\nWhen to use vibe coding:\n- Building ideas quickly\n- Prototypes and small apps\n\nBest approach:\n- Learn the basics the traditional way\n- Then use AI to go faster\n\nYou do not have to choose only one.', 'KnowCode Team', true),

  ('idea-to-app-with-ai', 'From Idea to App: Build Faster with AI', 'Turn a simple idea into a working app, step by step.', E'Have an idea? Here is how to build it with AI help.\n\n1. Write the idea in one line\n- Example: "an app to track my study hours"\n\n2. List the main screens\n- Home, add entry, see history\n\n3. Build one screen at a time\n- Ask AI for a starting point\n- Test it, then move on\n\n4. Connect a database\n- Save and load real data\n\n5. Make it look clean\n- Simple colors and spacing\n\n6. Share it\n- Put it online, get feedback\n\nKeep each step small. Small steps finish big projects.', 'KnowCode Team', true),

  ('design-basics-look-good', 'Design Basics: Make Anything Look Good', 'Five simple rules to make your apps and pages look clean.', E'You do not need to be an artist. Follow these simple rules.\n\n1. Use space\n- Give things room to breathe\n- Crowded looks messy\n\n2. Pick 2 colors\n- One main color, one accent\n- Use them consistently\n\n3. Keep text simple\n- One clear font\n- Big titles, readable body\n\n4. Line things up\n- Align edges\n- Neat = professional\n\n5. Make buttons obvious\n- Clear label\n- Stand-out color\n\nGood design is mostly simple choices, repeated. Start with these five.', 'KnowCode Team', true)
on conflict (slug) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  content = excluded.content,
  author = excluded.author,
  published = excluded.published;
